### ISSUE TITLE
Suggestion - Make all headings anchor links

### ISSUE THREAD

**Issue by calumjs** [SSWConsulting/SSW.Rules.Content#1801] opened 2021-09-26 23:41 UTC
Some rules are long, and you just want to draw attention to a specific part of it.

e.g. I want to recommend that someone adds more detail to a done email...I would like to point them to tip #2 on this page: https://www.ssw.com.au/rules/dones-do-you-reply-done-and-delete-the-original-email

Right now I need to say, go read this rule and pay special attention to the second tip...which is kind of annoying.

It would be cool if I could give them a link directly to tip #2 e.g. https://www.ssw.com.au/rules/dones-do-you-reply-done-and-delete-the-original-email#tip-2-provide-details-in-your-done 

Also - when I hover over a heading I'd like to see a link icon that indicates clicking on it will copy the anchor link...to see what I mean go to any Microsoft docs page e.g. https://docs.microsoft.com/en-us/sharepoint/introduction and hover on a heading.

Here is a rule about it too 😁 https://www.ssw.com.au/rules/do-you-know-how-to-use-named-anchor-links

**Comment by bradystroud** [comment] 2021-11-02 08:22
Duplicate of SSWConsulting/SSW.Rules/issues/701

**Comment by JackDevAU** [comment] 2021-11-26 00:31
Closing issue as this is a duplicate of [#701](SSWConsulting/SSW.Rules/issues/701)

**Closed by JackDevAU** 2021-11-26 00:31 UTC
