### ISSUE TITLE
Bug - Content showing blank on netlify mode 

### ISSUE THREAD

**Issue by jontygardner** [SSWConsulting/SSW.Rules.Content#2496] opened 2022-03-01 01:30 UTC
Cc: @tiagov8 @adamcogan @UlyssesMaclaren
  
(Checked by Tiago)

Hi @bradystroud 

**RE: SSW.Rules | Tabs - Do you add the right tabs when creating a new Teams conversation?**
  
I am trying to update the acknowledgments on this rule - https://www.ssw.com.au/rules/teams-add-the-right-tabs 

When I hit edit via netlify I don't see any content at all. I tested other netlify and it was all working fine. I know I could do this via GitHub, but as per my conversation with Tiago since there is a bug we decided to log this as an issue. 

1. Please investigate and fix 
2. Tell me to update acknowledgments once the bug is fixed  

![image](https://user-images.githubusercontent.com/97415708/156087397-28a9a1dc-6062-44ff-8dae-3746131785a0.png)
**Figure: No content showing for me to edit**

**Comment by bradystroud** [comment] 2022-03-01 01:44
Hi @jontygardner

This bug is caused by the URI being different to the folder name of the rule.
I have fixed this in PR #2497

Once that PR is merged, you can edit the acknowledgements using Netlify CMS normally.

Let me know if you have any more problems 🙂

**Closed** 2022-03-02 21:36 UTC
